using System.Text.Json;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YatraBackend.Database;
using YatraBackend.Services;

namespace YatraBackend.Controllers;

[ApiController]
[Route("api/[controller]")]
public class ScriptsController(ApplicationDbContext dbContext) : ControllerBase
{
    [HttpPost("[action]")]
    public async Task<IActionResult> Finance()
    {
        var financeMetadata = new string[]
        {
            "Finance",
            "Application",
            "Machine Learning",
            "Predictive Analytics",
            "Financial Data",
            "Investment",
            "Portfolio Management",
            "Risk Assessment",
            "Algorithmic Trading",
            "Asset Allocation",
            "Financial Modeling",
            "Data Analysis",
            "Predictive Modeling",
            "Trading Strategies",
            "Market Trends",
            "Financial Forecasting",
            "Decision Support",
            "Investment Strategies",
            "Quantitative Analysis",
            "Market Analysis",
            "Portfolio Optimization",
            "Risk Management",
            "Financial Planning",
            "Stock Market",
            "Cryptocurrency",
            "Financial Algorithms",
            "Data Mining",
            "Sentiment Analysis",
            "Credit Scoring",
            "Fraud Detection",
            "Real-time Data",
            "Market Volatility",
            "Economic Indicators",
            "Trading Signals",
            "Pattern Recognition",
            "Financial Services",
            "Performance Evaluation",
            "Trading Platform",
            "Backtesting",
            "Robo-Advisors",
            "Wealth Management",
            "Equity Research",
            "Financial Technology (FinTech)",
            "Alternative Data",
            "Capital Markets",
            "Fundamental Analysis",
            "Technical Analysis",
            "Market Liquidity",
            "Financial Instruments",
            "Automated Trading",
            "QR Payments",
            "Online Banking",
            "Payment Processing",
            "Digital Wallets",
            "Transaction Security",
            "Account Management",
            "Mobile Banking",
            "Bill Payment",
            "Fund Transfers",
            "Account Alerts",
            "Assets",
            "Liabilities",
            "Investment",
            "Portfolio",
            "Equity",
            "Interest",
            "Capital",
            "Revenue",
            "Budget",
            "Stocks",
            "Bonds",
            "Mutual Funds",
            "Retirement",
            "Savings",
            "Cash Flow",
            "Credit",
            "Debt",
            "Mortgage",
            "Insurance",
            "Taxation",
            "Financial Planning",
            "Risk Management",
            "Asset Allocation",
            "Dividends",
            "Inflation",
            "Economic Indicators",
            "Market Analysis",
            "Hedge Funds",
            "Derivatives",
            "Commodities",
            "Foreign Exchange (Forex)",
            "Options",
            "Futures",
            "Initial Public Offering (IPO)",
            "Securities",
            "Exchange-Traded Funds (ETFs)",
            "Real Estate",
            "Venture Capital",
            "Angel Investors",
            "Crowdfunding",
            "Capital Gains",
            "Depreciation",
            "Audit",
            "Balance Sheet",
            "Income Statement",
            "Cash Flow Statement",
            "Financial Statements",
            "Gross Margin",
            "Net Income",
            "Return on Investment (ROI)",
            "Compound Interest",
            "Amortization",
            "Financial Ratio",
            "Liquidity",
            "Solvency",
            "Debt-to-Equity Ratio",
            "Working Capital",
            "Enterprise Value",
            "Price-to-Earnings Ratio (P/E Ratio)",
            "Dividend Yield",
            "Market Capitalization",
            "Arbitrage",
            "Blue Chip Stocks",
            "Bull Market",
            "Bear Market",
            "Economic Recession",
            "Economic Recovery",
            "Fiscal Policy",
            "Monetary Policy",
            "Central Bank",
            "Federal Reserve",
            "Interest Rate",
            "Stock Market",
            "Bond Market",
            "Capital Market",
            "Money Market",
            "Exchange Rate",
            "Financial Institution",
            "Commercial Bank",
            "Investment Bank",
            "Hedge Fund Manager",
            "Financial Analyst",
            "Accountant",
            "Auditor",
            "Economist",
            "Financial Advisor",
            "Stockbroker",
            "Portfolio Manager",
            "Risk Analyst",
            "Actuary",
            "Tax Advisor",
            "Asset Manager",
            "Private Equity",
            "Valuation",
            "Due Diligence",
            "Financial Modeling",
            "Merger and Acquisition (M&A)",
            "Initial Coin Offering (ICO)",
            "Cryptocurrency",
            "Blockchain"
            
        };

        var domain = await dbContext.Domains
            .Where(x => x.Name.Equals("Finance"))
            .FirstOrDefaultAsync();

        domain.Metadata = financeMetadata.ToList();

        dbContext.Update(domain);
        await dbContext.SaveChangesAsync();

        return Ok();
    }

    [HttpPost("[action]")]
    public async Task<IActionResult> Health()
    {
        var healthMetadata = new string[]
        {
            "Healthcare",
            "Medical",
            "Health",
            "Telemedicine",
            "Electronic Health Records",
            "EHR",
            "Medical Imaging",
            "Health Information Technology",
            "Health Data",
            "Patient Care",
            "Clinical Decision Support",
            "Health Monitoring",
            "Medical Devices",
            "Remote Patient Monitoring",
            "Health Informatics",
            "Medical Records",
            "Health Analytics",
            "Health Management",
            "Health Apps",
            "Health Wearables",
            "Medical Diagnosis",
            "Disease Management",
            "Healthcare Technology",
            "Digital Health",
            "Health Information Exchange",
            "Medical Sensors",
            "Health Tracking",
            "Health Sensors",
            "Health AI",
            "Medical Research",
            "Healthcare Innovation",
            "Medical Software",
            "Health Education",
            "Population Health",
            "Public Health",
            "Health IT",
            "Healthcare Analytics",
            "Healthcare Management",
            "Healthcare Services",
            "Healthcare Apps",
            "Clinical Data",
            "Healthcare Systems",
            "Healthcare Solutions",
            "Healthcare Providers",
            "Healthcare Industry",
            "Healthcare Informatics",
            "Medical Technology",
            "Health Tech",
            "Healthcare Delivery",
            "Healthcare Professionals",
            "Medical Informatics",
            "Healthcare Data",
            "Healthcare Trends",
            "Patient Engagement",
            "Wellness",
            "Nutrition",
            "Exercise",
            "Healthcare",
            "Immunity",
            "Disease",
            "Mental Health",
            "Hygiene",
            "Rehabilitation",
            "Prevention",
            "Wellness Program",
            "Health Promotion",
            "Public Health",
            "Epidemiology",
            "Vaccination",
            "Immunization",
            "Chronic Disease",
            "Acute Illness",
            "Primary Care",
            "Specialist",
            "Hospital",
            "Clinic",
            "Emergency Room",
            "Surgery",
            "Prescription",
            "Medication",
            "Pharmaceutical",
            "Medical Device",
            "Diagnostic Test",
            "Medical Imaging",
            "Laboratory",
            "Blood Pressure",
            "Heart Rate",
            "Cholesterol",
            "Blood Sugar",
            "Body Mass Index (BMI)",
            "Dietitian",
            "Nutritionist",
            "Exercise Physiology",
            "Physical Therapy",
            "Occupational Therapy",
            "Speech Therapy",
            "Respiratory Therapy",
            "Cardiology",
            "Neurology",
            "Oncology",
            "Pediatrics",
            "Geriatrics",
            "Obstetrics",
            "Gynecology",
            "Psychiatry",
            "Psychology",
            "Counseling",
            "Psychotherapy",
            "Mental Health Counseling",
            "Substance Abuse",
            "Addiction",
            "Rehabilitation Center",
            "Therapy",
            "Support Group",
            "Health Insurance",
            "Health Savings Account (HSA)",
            "Medical Billing",
            "Health Information Management",
            "Electronic Health Record (EHR)",
            "Telemedicine",
            "Telehealth",
            "Health Technology",
            "Health Education",
            "Health Literacy",
            "Health Equity",
            "Social Determinants of Health",
            "Health Behavior",
            "Lifestyle Medicine",
            "Holistic Health",
            "Alternative Medicine",
            "Integrative Medicine",
            "Traditional Medicine",
            "Ayurveda",
            "Traditional Chinese Medicine (TCM)",
            "Homeopathy",
            "Naturopathy",
            "Chiropractic",
            "Massage Therapy",
            "Acupuncture",
            "Herbal Medicine",
            "Dietary Supplements",
            "Functional Medicine",
            "Preventive Medicine",
            "Community Health",
            "Occupational Health",
            "Environmental Health",
            "Maternal Health",
            "Child Health",
            "Adolescent Health",
            "Senior Health",
            "Global Health",
            "Health Policy",
            "Healthcare Administration",
            "Healthcare Management",
        };

        var domain = await dbContext.Domains
            .Where(x => x.Name == "Health")
            .FirstOrDefaultAsync();

        domain.Metadata = healthMetadata.ToList();

        dbContext.Domains.Update(domain);
        await dbContext.SaveChangesAsync();

        return Ok();
    }

    [HttpGet("[action]/{id:guid}")]
    public async Task<IActionResult> Recommend(Guid id)
    {
        var query = await dbContext.Metadatas
            .FirstOrDefaultAsync(x => x.Id == id);

        var metadata = await dbContext.Metadatas
            .Where(x => x.Id != id)
            .ToListAsync();

        var result = MLHelper.Recommend(query, metadata);
        
        return Ok(result);
    }
}